FROM python:3.10

WORKDIR /app

COPY mapSearch/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY mapSearch/ .

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
